export const SECTOR_TRANSLATIONS: Record<string, string> = {
    "Energy": "能源",
    "Banking": "銀行",
    "Information & Communication Technology": "資通訊",
    "ICT": "資通訊",
    "Transportation & Logistics": "運輸物流",
    "Transport": "運輸物流",
    "Commerce": "商業",
    "Property Development": "地產開發",
    "Property": "地產",
    "Food & Beverage": "食品飲料",
    "Food": "食品",
    "Health Care Services": "醫療服務",
    "Health Care": "醫療",
    "Construction Services": "營建服務",
    "Construction": "營建",
    "Electronic Components": "電子零組件",
    "Resources": "資源",
    "Services": "服務",
    "Technology": "科技",
    "Financials": "金融",
    "Agro & Food Industry": "農工食品",
    "Industrials": "工業",
    "Consumer Products": "消費品",
    "Property & Construction": "地產營建",
    "Utilities": "公用事業",
    "Petrochemicals & Chemicals": "石化化工",
    "Packaging": "包裝",
    "Fashion": "時尚",
    "Home & Office Products": "家居辦公",
    "Personal Products & Pharmaceuticals": "個人護理與醫藥",
    "Professional Services": "專業服務",
    "Media & Publishing": "媒體出版",
    "Tourism & Leisure": "旅遊休閒",
    "Automotive": "汽車",
    "Industrial Materials": "工業材料",
    "Paper & Printing Materials": "造紙印刷",
    "Steel": "鋼鐵",
};

export const UI_LABELS = {
    YIELD: "殖利率",
    PE: "本益比",
    PB: "股價淨值比",
    MARKET_CAP: "市值",
    REAL_TIME: "即時",
    AVG_YIELD_5Y: "5年平均殖利率",
    PAYOUT_RATIO: "配息率",
    PROFIT_GROWTH: "獲利成長",
    FAIR_VALUE: "合理價",
    UNDERVALUED: "被低估",
    FAIR: "合理",
    OVERVALUED: "被高估",
    EXTREME_CHEAP: "極度便宜",
};
